### ISSUE TITLE
Problem with Maybe's unbox method signature

### ISSUE THREAD

**Issue by vegansk** [superfunc/monad#1]
Hello.

Unbox signature must contain return type, like this:

    proc unbox*[T](m: Maybe[T])*: T* =

, or the compiler raises discard error on method use

**Comment by superfunc** [comment]
Thanks for raising an issue. I'm completely revamping the library. Should be put in in the next couple of days.

**Comment by superfunc** [comment]
I just wanted to come by and apologize for the lack of updates. My internship has taken up 10x more of my energy than I had initially anticipated. I'm going to do my best to get it done this week.
